import XCTest

/// Store-submission configuration. Both Info.plists are generated by xcodegen
/// from project.yml, so the plist assertions check the generated output and
/// the yml assertions check the source of truth.
final class ReleaseConfigurationTests: XCTestCase {
    private static let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()

    private func text(_ path: String) throws -> String {
        try String(contentsOf: Self.root.appendingPathComponent(path), encoding: .utf8)
    }

    private func plist(_ path: String) throws -> [String: Any] {
        let data = try Data(contentsOf: Self.root.appendingPathComponent(path))
        return try XCTUnwrap(PropertyListSerialization.propertyList(from: data, format: nil) as? [String: Any])
    }

    func testReleaseIsNotPinnedToADevelopmentSigningIdentity() throws {
        let yml = try text("project.yml")
        let base = try XCTUnwrap(yml.range(of: "settings:\n  base:\n"))
        let configs = try XCTUnwrap(yml.range(of: "  configs:\n"))
        let baseBlock = String(yml[base.upperBound..<configs.lowerBound])
        XCTAssertFalse(baseBlock.contains("CODE_SIGN_IDENTITY"), "a base identity applies to Release archives too")
        let release = try XCTUnwrap(yml.range(of: "    Release:\n      APS_ENVIRONMENT: production\n"))
        let afterRelease = String(yml[release.upperBound...].prefix(120))
        XCTAssertFalse(afterRelease.contains("CODE_SIGN_IDENTITY"))
    }

    func testExtensionVersionTracksTheApp() throws {
        let app = try plist("Info.plist")
        let appex = try plist("SanchrShareExtension/Info.plist")
        for (name, info) in [("app", app), ("extension", appex)] {
            XCTAssertEqual(info["CFBundleShortVersionString"] as? String, "$(MARKETING_VERSION)", name)
            XCTAssertEqual(info["CFBundleVersion"] as? String, "$(CURRENT_PROJECT_VERSION)", name)
        }
        let yml = try text("project.yml")
        XCTAssertEqual(yml.components(separatedBy: "MARKETING_VERSION: \"1.0.0\"").count - 1, 2,
                       "app and extension declare the same marketing version")
    }

    func testLaunchScreenCategoryAndBackgroundModes() throws {
        let app = try plist("Info.plist")
        XCTAssertNil(app["UILaunchStoryboardName"], "an empty storyboard name means no launch screen")
        let launch = try XCTUnwrap(app["UILaunchScreen"] as? [String: Any])
        XCTAssertEqual(launch["UIColorName"] as? String, "LaunchBackground")
        XCTAssertTrue(FileManager.default.fileExists(
            atPath: Self.root.appendingPathComponent("Resources/Assets.xcassets/LaunchBackground.colorset/Contents.json").path))
        XCTAssertEqual(app["LSApplicationCategoryType"] as? String, "public.app-category.social-networking")
        let modes = try XCTUnwrap(app["UIBackgroundModes"] as? [String])
        XCTAssertTrue(modes.contains("voip") && modes.contains("audio"), "calls need both: \(modes)")
    }

    func testCameraStringDoesNotPromiseVideoCalls() throws {
        let app = try plist("Info.plist")
        let camera = try XCTUnwrap(app["NSCameraUsageDescription"] as? String)
        XCTAssertFalse(camera.localizedCaseInsensitiveContains("video call"), "release disables video calling")
    }
}
