import UIKit
import XCTest

/// Every SF Symbol name used in the app, checked in one place.
///
/// A wrong name fails silently — SwiftUI renders an empty space rather than
/// complaining — which is how `circle.badge.fill` reached the sort menu and was
/// only noticed by eye. `UIImage(systemName:)` returns nil for a name the
/// system does not know, so a typo becomes a test failure instead of a blank
/// icon someone has to spot.
///
/// The list is generated by grepping `systemName:` literals. When a new symbol
/// is introduced, add it here.
final class SFSymbolAvailabilityTests: XCTestCase {

    private let symbolsUsedInTheApp: [String] = [
        // Help Center categories, topics and community rows.
        "sparkles", "lock", "gearshape", "questionmark.circle", "phone", "person.3",
        "eye.slash", "clock.arrow.circlepath", "icloud.and.arrow.up", "headphones",
        "at", "bubble.left.and.bubble.right", "text.bubble", "arrow.up.right", "message", "envelope",
        "arrow.clockwise",
        "arrow.clockwise.circle",
        "arrow.clockwise.circle.fill",
        "arrow.counterclockwise",
        "arrow.down.circle.fill",
        "arrow.down.to.line",
        "arrow.left",
        "arrow.right",
        "arrow.triangle.2.circlepath",
        "arrow.triangle.turn.up.right.circle.fill",
        "arrow.up",
        "arrow.up.circle.fill",
        "arrow.up.right",
        "arrow.uturn.backward",
        "arrowshape.turn.up.left",
        "arrowshape.turn.up.left.fill",
        "arrowshape.turn.up.right",
        "bell.badge.fill",
        "bell.slash",
        "bell.slash.fill",
        "bubble.left.fill",
        "camera.fill",
        "chart.line.uptrend.xyaxis",
        "checkmark",
        "checkmark.circle.fill",
        "checkmark.message",
        "checkmark.shield.fill",
        "chevron.down",
        "chevron.left",
        "chevron.right",
        "chevron.up",
        "circle",
        "clock",
        "clock.arrow.circlepath",
        "delete.left",
        "doc.fill",
        "doc.on.doc",
        "ellipsis",
        "ellipsis.circle",
        "ellipsis.rectangle.fill",
        "envelope",
        "exclamationmark.circle",
        "exclamationmark.circle.fill",
        "exclamationmark.shield.fill",
        "exclamationmark.triangle",
        "exclamationmark.triangle.fill",
        "externaldrive.badge.exclamationmark",
        "eye.slash",
        "face.smiling",
        "faceid",
        "globe",
        "globe.europe.africa.fill",
        "hand.raised.slash",
        "headphones",
        "info.circle.fill",
        "internaldrive",
        "lock.doc.fill",
        "lock.fill",
        "lock.rectangle",
        "lock.shield",
        "lock.shield.fill",
        "magnifyingglass",
        "mappin.and.ellipse",
        "message.fill",
        "mic.fill",
        "music.note",
        "paperplane",
        "person",
        "person.2.fill",
        "person.2.slash",
        "person.3.fill",
        "person.badge.plus",
        "person.crop.circle.fill",
        "person.fill",
        "person.slash.fill",
        "phone.badge.plus",
        "phone.fill.badge.plus",
        "photo",
        "photo.on.rectangle.angled",
        "play.circle.fill",
        "play.fill",
        "plus",
        "qrcode",
        "qrcode.viewfinder",
        "record.circle",
        "shield",
        "shield.fill",
        "slider.horizontal.3",
        "square.and.arrow.up",
        "stop.fill",
        "text.bubble.fill",
        "trash",
        "video.fill",
        "video.slash.fill",
        "waveform",
        "xmark",
        "xmark.circle",
        "xmark.circle.fill"
    ]

    func testEverySymbolResolvesOnTheDeploymentTarget() {
        var missing: [String] = []
        for name in symbolsUsedInTheApp where UIImage(systemName: name) == nil {
            missing.append(name)
        }
        XCTAssertTrue(
            missing.isEmpty,
            "these render as blank space: \(missing.sorted().joined(separator: ", "))"
        )
    }
}
